name: Build and Run FraudEngine Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4

    - name: Checkout Test Repository
      uses: actions/checkout@v4
      with:
        repository: 'BenjyMabety/FraudEngine.Tests'
        ref: 'master'
        path: 'FraudEngine.Tests'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Main Engine
      run: dotnet restore CapitecFraudEngine.csproj

    - name: Build Main Engine
      run: dotnet build CapitecFraudEngine.csproj --no-restore --configuration Release

    - name: Restore and Run Tests
      run: dotnet test FraudEngine.Tests/FraudEngine.Tests/FraudEngine.Tests.csproj --configuration Release --verbosity normal